[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.86"
repository = "https://github.com/jpvanegasc/enigma"
authors = ["jpvanegasc"]

[workspace.dependencies]
enigma = {path = "crates/enigma"}
turing = {path = "crates/turing"}
